import { QuestionType } from "../src/generated/prisma/client";

export type InterviewSeedQuestion = {
  categorySlug: string;
  title: string;
  prompt: string;
  roundLabel: string;
  tags: string;
  type: QuestionType;
  idealAnswer: string;
  explanation: string;
  choices?: { label: string; isCorrect: boolean }[];
};

/**
 * Medical imaging interview Q&A imported from
 * https://github.com/amine0110/Medical-Imaging-Interview-Questions-Answers
 * (full answers from pycad.co). Near-duplicates vs existing bank skipped:
 * Q6 class imbalance, Q15/Q32 metrics overview, Q17 U-Net.
 */
export const interviewQuestionsEn: InterviewSeedQuestion[] = [
  {
    categorySlug: "medical-data",
    title: "What is medical imaging and why is it important in healthcare",
    prompt: "What is medical imaging and why is it important in healthcare?",
    roundLabel: "MI-Q1",
    tags: "Medical Imaging Basics",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Medical imaging refers to the process of creating visual representations of the interior of a body for clinical analysis and medical intervention. It encompasses a wide range of techniques, including X-rays, computed tomography (CT), magnetic resonance imaging (MRI), ultrasound, and nuclear medicine, among others.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ct-mri",
    title: "What are the different types of medical imaging techniques? Explain each briefly",
    prompt: "What are the different types of medical imaging techniques? Explain each briefly.",
    roundLabel: "MI-Q2",
    tags: "Modalities CT MRI X-ray",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "There are several types of medical imaging techniques, each with its specific applications and benefits. Here’s a brief explanation of some of the most common techniques:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "How do you handle missing or corrupted data in a dataset",
    prompt: "How do you handle missing or corrupted data in a dataset?",
    roundLabel: "MI-Q3",
    tags: "Data Quality Missing Data",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Handling missing or corrupted data is a crucial aspect of data preprocessing in any data science project, including medical imaging. Here are some common strategies to address this issue:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "dicom",
    title: "What is DICOM? Explain its significance in medical imaging",
    prompt: "What is DICOM? Explain its significance in medical imaging.",
    roundLabel: "MI-Q4",
    tags: "DICOM Standards",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "DICOM (Digital Imaging and Communications in Medicine) is a standard for transmitting, storing, retrieving, and sharing medical images and related information. Developed by the National Electrical Manufacturers Association (NEMA) and the American College of Radiology (ACR), DICOM is widely used in medical imaging to ensure interoperability between different imaging devices, PACS (Picture Archiving and Communication Systems), and healthcare information systems.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Explain the concepts of precision, recall, and F1 score in the context of medical image analysis",
    prompt: "Explain the concepts of precision, recall, and F1 score in the context of medical image analysis.",
    roundLabel: "MI-Q5",
    tags: "Metrics Precision Recall",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Precision, recall, and F1 score are performance metrics used to evaluate the effectiveness of classification models, including those applied to medical image analysis tasks like tumor detection, lesion segmentation, or disease classification. These metrics provide insights into the model’s accuracy, sensitivity, and overall performance.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What is the role of convolutional neural networks (CNNs) in medical image analysis",
    prompt: "What is the role of convolutional neural networks (CNNs) in medical image analysis?",
    roundLabel: "MI-Q7",
    tags: "CNNs Deep Learning",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Convolutional neural networks (CNNs) are a class of deep learning models designed to process grid-like data, such as images. They have shown exceptional performance in various image analysis tasks, including classification, segmentation, and object detection. In medical image analysis, CNNs play a significant role in automating the detection, diagnosis, and prognosis of various medical conditions by processing and analyzing medical images. Some key roles of CNNs in medical image analysis include:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Explain the concept of transfer learning and its relevance in medical imaging tasks",
    prompt: "Explain the concept of transfer learning and its relevance in medical imaging tasks.",
    roundLabel: "MI-Q8",
    tags: "Transfer Learning",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Transfer learning is a machine learning technique that leverages knowledge acquired from one task or domain (source) to improve the performance of a model on a different but related task or domain (target). In the context of deep learning, transfer learning typically involves using pre-trained neural networks, often trained on large, general-purpose datasets, as a starting point for training a model on a specific task or dataset.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "dl-basics",
    title: "What is the difference between supervised, unsupervised, and semi-supervised learning",
    prompt: "What is the difference between supervised, unsupervised, and semi-supervised learning?",
    roundLabel: "MI-Q9",
    tags: "Learning Paradigms",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "These three terms represent different learning paradigms in machine learning, each with its distinct approach to learning from data.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "What are some common preprocessing techniques used in medical image analysis",
    prompt: "What are some common preprocessing techniques used in medical image analysis?",
    roundLabel: "MI-Q10",
    tags: "Preprocessing",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Preprocessing is a crucial step in medical image analysis, as it helps to standardize and enhance the quality of the input images, ultimately improving the performance of subsequent analysis tasks. Some common preprocessing techniques used in medical image analysis include:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "Describe the process of data augmentation and why it’s important in medical image analysis",
    prompt: "Describe the process of data augmentation and why it’s important in medical image analysis.",
    roundLabel: "MI-Q11",
    tags: "Data Augmentation",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Data augmentation is a technique used to increase the size and diversity of a training dataset by creating new instances through the application of various transformations to the original data. In the context of medical image analysis, data augmentation typically involves applying image transformations, such as rotations, translations, scaling, flipping, or elastic deformations, to generate new, altered versions of the original medical images.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What is image segmentation? Explain its significance in medical imaging",
    prompt: "What is image segmentation? Explain its significance in medical imaging.",
    roundLabel: "MI-Q12",
    tags: "Segmentation",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Image segmentation is the process of dividing an image into multiple regions or segments, each of which consists of a group of pixels with similar characteristics or properties. The goal is to separate objects or regions of interest (ROIs) from the background or other objects in the image, simplifying the image for further analysis or interpretation.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "Describe the role of edge detection in medical image analysis",
    prompt: "Describe the role of edge detection in medical image analysis.",
    roundLabel: "MI-Q13",
    tags: "Edge Detection",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Edge detection is an image processing technique that identifies the boundaries or edges between different regions in an image. These boundaries typically correspond to areas where there is a significant change in pixel intensity or color, indicating a transition between different objects or structures. In medical image analysis, edge detection plays an important role in various tasks, such as:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "What are some common challenges faced in medical image analysis",
    prompt: "What are some common challenges faced in medical image analysis?",
    roundLabel: "MI-Q14",
    tags: "Challenges",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Medical image analysis is a complex and critical task, as it often deals with high-dimensional and heterogeneous data, and its outcomes can significantly impact diagnosis, treatment, and patient care. Some common challenges faced in medical image analysis include:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Explain the difference between semantic segmentation and instance segmentation",
    prompt: "Explain the difference between semantic segmentation and instance segmentation.",
    roundLabel: "MI-Q16",
    tags: "Semantic vs Instance",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Semantic segmentation and instance segmentation are two related tasks in computer vision and image analysis, with the primary goal of partitioning an image into meaningful regions or segments. However, they differ in their objectives and granularity of the segmentation:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "Describe the process of image registration in medical imaging",
    prompt: "Describe the process of image registration in medical imaging.",
    roundLabel: "MI-Q18",
    tags: "Registration",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Image registration is a critical process in medical imaging that involves aligning and superimposing two or more images, often acquired from different imaging modalities (e.g., MRI, CT, PET), time points (e.g., pre- and post-treatment), or perspectives. The goal of image registration is to establish spatial correspondences between the images, enabling the analysis and integration of complementary information from the different images. Image registration is widely used in various medical applications, such as image-guided surgery, treatment planning, monitoring disease progression, and studying the structure and function of the human body.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What is the role of Generative Adversarial Networks (GANs) in medical imaging",
    prompt: "What is the role of Generative Adversarial Networks (GANs) in medical imaging?",
    roundLabel: "MI-Q19",
    tags: "GANs",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Generative Adversarial Networks (GANs) are a class of deep learning models introduced by Ian Goodfellow and his colleagues in 2014. GANs consist of two neural networks, a generator and a discriminator, that are trained together in a game-theoretic adversarial process. The generator learns to create synthetic data samples, while the discriminator learns to distinguish between real and synthetic data samples. As the training progresses, the generator becomes better at generating realistic samples, and the discriminator becomes better at identifying them, resulting in a generator capable of producing high-quality synthetic data.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Explain the concept of feature extraction in medical imaging",
    prompt: "Explain the concept of feature extraction in medical imaging.",
    roundLabel: "MI-Q20",
    tags: "Feature Extraction",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Feature extraction is a critical step in medical image analysis that involves identifying and extracting meaningful and informative features or attributes from the images. These features serve as a compact and representative description of the image content, capturing relevant patterns, structures, or properties that can be used for various tasks, such as classification, segmentation, registration, or retrieval. Feature extraction helps reduce the dimensionality of the data, mitigates the effects of noise and variations, and enhances the efficiency and performance of machine learning models.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "How do you approach handling large datasets in medical imaging projects",
    prompt: "How do you approach handling large datasets in medical imaging projects?",
    roundLabel: "MI-Q21",
    tags: "Large Datasets",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Handling large datasets in medical imaging projects can be challenging due to the high resolution of medical images, the diverse range of imaging modalities, and the need for efficient storage, processing, and analysis of the data. Here are some strategies for managing large datasets in medical imaging projects:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "governance",
    title: "What are some ethical considerations in medical image analysis",
    prompt: "What are some ethical considerations in medical image analysis?",
    roundLabel: "MI-Q22",
    tags: "Ethics",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Ethical considerations in medical image analysis are essential to ensure that the development and deployment of these technologies are responsible, safe, and beneficial to patients and healthcare providers. Some key ethical concerns include:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "governance",
    title: "How do you ensure patient privacy when working with medical imaging data",
    prompt: "How do you ensure patient privacy when working with medical imaging data?",
    roundLabel: "MI-Q23",
    tags: "Privacy HIPAA GDPR",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Ensuring patient privacy when working with medical imaging data is crucial to comply with data protection regulations and maintain trust with patients and healthcare providers. Here are some strategies to protect patient privacy in medical imaging projects:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ct-mri",
    title: "What is the difference between 2D, 3D, and 4D medical imaging",
    prompt: "What is the difference between 2D, 3D, and 4D medical imaging?",
    roundLabel: "MI-Q24",
    tags: "2D 3D 4D",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Medical imaging is used to capture visual representations of anatomical structures, physiological functions, and pathological conditions of the human body. The dimensionality of the image refers to the number of spatial dimensions that are represented in the image. Here is a brief explanation of the differences between 2D, 3D, and 4D medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ct-mri",
    title: "Explain the concept of multi-modal medical imaging and its benefits",
    prompt: "Explain the concept of multi-modal medical imaging and its benefits.",
    roundLabel: "MI-Q25",
    tags: "Multi-modal Imaging",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Multi-modal medical imaging involves combining data from different imaging modalities to create a more comprehensive and accurate representation of the human body. This approach can provide complementary information about the anatomical and functional characteristics of organs and tissues, improving diagnostic accuracy and treatment planning. Here are some benefits of multi-modal medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "How do you handle overfitting in machine learning models for medical imaging",
    prompt: "How do you handle overfitting in machine learning models for medical imaging?",
    roundLabel: "MI-Q26",
    tags: "Overfitting Regularization",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Overfitting occurs when a machine learning model learns the training data too well, including noise and irrelevant features, resulting in poor performance on new, unseen data. Overfitting is a common problem in machine learning models for medical imaging, where the data may be complex, high-dimensional, and heterogeneous. Here are some strategies to prevent and mitigate overfitting in machine learning models for medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What is the role of reinforcement learning in medical imaging",
    prompt: "What is the role of reinforcement learning in medical imaging?",
    roundLabel: "MI-Q27",
    tags: "Reinforcement Learning",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Reinforcement learning is a subfield of machine learning that focuses on teaching an agent to make decisions by interacting with an environment and receiving feedback in the form of rewards or penalties. In medical imaging, reinforcement learning can be used to develop intelligent systems that learn to analyze medical images and make decisions based on clinical outcomes. Here are some examples of the role of reinforcement learning in medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Describe the concept of Radiomics and its significance in medical imaging",
    prompt: "Describe the concept of Radiomics and its significance in medical imaging.",
    roundLabel: "MI-Q28",
    tags: "Radiomics",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Radiomics is a field of medical imaging that involves the extraction and analysis of quantitative features from medical images to help diagnose, classify, and predict disease outcomes. Radiomics uses advanced machine learning algorithms to identify and quantify imaging biomarkers, such as texture, shape, and intensity, that are associated with specific diseases or conditions. Here are some key concepts and significance of radiomics in medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "Explain the importance of data normalization in medical imaging projects",
    prompt: "Explain the importance of data normalization in medical imaging projects.",
    roundLabel: "MI-Q29",
    tags: "Normalization",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Data normalization is an essential preprocessing step in medical imaging projects that involves scaling the input data to a common range or distribution. The purpose of data normalization is to remove variations in the data that are not related to the underlying biological or physiological processes and to improve the performance and interpretability of machine learning models. Here are some key reasons why data normalization is important in medical imaging projects:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What are some applications of deep learning in medical imaging",
    prompt: "What are some applications of deep learning in medical imaging?",
    roundLabel: "MI-Q30",
    tags: "Deep Learning Applications",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Deep learning is a subset of machine learning that involves the use of deep neural networks with multiple layers to learn representations of data. In medical imaging, deep learning has shown great promise in improving the accuracy and efficiency of various tasks, including image classification, segmentation, registration, and analysis. Here are some examples of the applications of deep learning in medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "medical-data",
    title: "How do you deal with noisy or low-quality medical images",
    prompt: "How do you deal with noisy or low-quality medical images?",
    roundLabel: "MI-Q31",
    tags: "Noise Artifacts",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Medical images may often be of poor quality, which can be caused by several factors, such as the limitations of the imaging equipment, patient movement, and artifacts from image reconstruction. The presence of noise or other distortions in the images can adversely affect the performance of machine learning models used in medical image analysis. Here are some strategies for dealing with noisy or low-quality medical images:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What is the role of natural language processing in medical imaging?",
    prompt: "What is the role of natural language processing in medical imaging?",
    roundLabel: "MI-Q33",
    tags: "NLP Reports",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Natural language processing (NLP) extracts and analyzes text-based clinical data (radiology reports, EHRs, notes) and can integrate it with image-based information.\n1. Radiology report analysis: extract findings/impressions and link them to imaging.\n2. Clinical decision support: surface history, meds, and allergies to guide imaging choices.\n3. Image annotation: attach structure/finding/diagnosis labels from text.\n4. Automated report generation: draft consistent reports from imaging + clinical context.\n5. Quality assurance: flag missed findings, inconsistencies, or report discrepancies.",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Explain the concept of computer-aided diagnosis (CAD) in medical imaging",
    prompt: "Explain the concept of computer-aided diagnosis (CAD) in medical imaging.",
    roundLabel: "MI-Q34",
    tags: "CAD",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Computer-aided diagnosis (CAD) is a technique that uses machine learning algorithms and other computational methods to assist radiologists and other healthcare professionals in the diagnosis and interpretation of medical images. CAD systems analyze medical images and provide quantitative and qualitative information to support the decision-making process. Here are some key features of CAD in medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Describe the difference between image classification, object detection, and image segmentation",
    prompt: "Describe the difference between image classification, object detection, and image segmentation.",
    roundLabel: "MI-Q35",
    tags: "Classification Detection Segmentation",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Image classification, object detection, and image segmentation are three fundamental tasks in computer vision, including medical imaging. Here are the main differences between these three tasks:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "How do you handle false positives and false negatives in medical image analysis",
    prompt: "How do you handle false positives and false negatives in medical image analysis?",
    roundLabel: "MI-Q36",
    tags: "False Positives Negatives",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "False positives and false negatives are common challenges in medical image analysis. False positives occur when the algorithm detects a lesion or abnormality that is not present, while false negatives occur when the algorithm misses a lesion or abnormality that is present. Here are some strategies to handle false positives and false negatives in medical image analysis:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What is the significance of multi-task learning in medical imaging",
    prompt: "What is the significance of multi-task learning in medical imaging?",
    roundLabel: "MI-Q37",
    tags: "Multi-task Learning",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Multi-task learning is a machine learning technique that enables the joint learning of multiple related tasks using a single model. In medical imaging, multi-task learning has gained increasing attention due to its ability to improve the accuracy and efficiency of medical image analysis. Here are some of the significant benefits of multi-task learning in medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "Explain the role of recurrent neural networks (RNNs) in medical imaging",
    prompt: "Explain the role of recurrent neural networks (RNNs) in medical imaging.",
    roundLabel: "MI-Q38",
    tags: "RNNs Temporal",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Recurrent neural networks (RNNs) are a class of neural networks that can process sequential data by maintaining a memory of previous inputs. In medical imaging, RNNs have been used in a variety of applications, including image and video analysis, time series prediction, and natural language processing. Here are some of the roles of RNNs in medical imaging:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "governance",
    title: "Describe the importance of collaboration between data scientists and medical professionals in medical imaging projects",
    prompt: "Describe the importance of collaboration between data scientists and medical professionals in medical imaging projects.",
    roundLabel: "MI-Q39",
    tags: "Interdisciplinary Collaboration",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Collaboration between data scientists and medical professionals is critical in medical imaging projects. Medical imaging is a complex and interdisciplinary field that requires expertise in both medicine and data science. Here are some of the reasons why collaboration between data scientists and medical professionals is essential in medical imaging projects:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  },
  {
    categorySlug: "ai-dl",
    title: "What are some recent advances and trends in medical image analysis",
    prompt: "What are some recent advances and trends in medical image analysis?",
    roundLabel: "MI-Q40",
    tags: "Trends Advances",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Medical image analysis is a rapidly evolving field with many recent advances and emerging trends. Here are some of the recent advances and trends in medical image analysis:",
    explanation: "Source: amine0110/Medical-Imaging-Interview-Questions-Answers (PYCAD full answers). Adapted for free-text assessment.",
  }
];
