import { QuestionType } from "../src/generated/prisma/client";

export type TutorSeedQuestion = {
  categorySlug: string;
  title: string;
  prompt: string;
  roundLabel: string;
  tags: string;
  type: QuestionType;
  idealAnswer: string;
  explanation: string;
  choices?: { label: string; isCorrect: boolean }[];
};

/** English Q&A ported from deep_learning_medizin_tutor.html (duplicates skipped). */
export const tutorQuestionsEn: TutorSeedQuestion[] = [
  {
    categorySlug: "dl-basics",
    title: "Why Linear Activations Fail in Deep Nets",
    prompt: "Why is a linear activation function useless for deep networks?",
    roundLabel: "Q1.1",
    tags: "Activations",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Composition of linear maps is still linear. A 50-layer net with \u03c6(z)=z collapses to a single linear transform \u2014 depth adds no expressive power. Nonlinearity is required for deeper layers to express new hypotheses.",
    explanation: "This is the classic argument for nonlinear activations (sigmoid, ReLU, etc.) in multilayer networks.",
  },
  {
    categorySlug: "dl-basics",
    title: "Does ReLU Solve Vanishing Gradients?",
    prompt: "Does ReLU solve the vanishing-gradient problem?",
    roundLabel: "Q1.2",
    tags: "ReLU & Gradients",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "Yes \u2014 ReLU fully solves vanishing gradients in any depth", isCorrect: false },
      { label: "Only partially; dying ReLU and very deep nets still need residuals/BN", isCorrect: true },
      { label: "No \u2014 ReLU makes vanishing gradients worse than sigmoid", isCorrect: false },
      { label: "Only if combined with softmax", isCorrect: false },
    ],
    idealAnswer: "Only partially. For z>0 the derivative is 1, which helps. For z<0 it is exactly 0 (dying ReLU). Very deep nets still need residual connections and/or batch norm. Saying \u201cReLU solves it\u201d is oversimplified.",
    explanation: "ReLU mitigates but does not eliminate optimization issues in deep networks.",
  },
  {
    categorySlug: "dl-basics",
    title: "Parameters vs Hyperparameters",
    prompt: "What is the difference between a parameter and a hyperparameter?",
    roundLabel: "Q1.3",
    tags: "Training Basics",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Parameters (weights, biases) are learned by the optimizer via gradient descent. Hyperparameters (learning rate, batch size, depth, dropout) are set by you before/during training and are not updated by backprop.",
    explanation: "Fine-tuning is often mostly about choosing good hyperparameters.",
  },
  {
    categorySlug: "dl-basics",
    title: "Loss Becomes NaN \u2014 Common Causes",
    prompt: "If training loss jumps to NaN, what are the three most common causes?",
    roundLabel: "Q1.4",
    tags: "Debugging",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "1) Learning rate too high (exploding updates). 2) Division by zero / log(0) in the loss (e.g. unstable CE). 3) Forgotten zero_grad() causing gradient accumulation. Bonus: inf/NaN values already in the input data.",
    explanation: "Systematic debugging of NaNs starts with LR, numerics in the loss, and optimizer step hygiene.",
  },
  {
    categorySlug: "dl-basics",
    title: "Sigmoid Derivative at z = 0",
    prompt: "Compute \u03c3'(z), the derivative of the sigmoid, at z = 0.",
    roundLabel: "Q1.5",
    tags: "Calculus",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "0", isCorrect: false },
      { label: "0.25", isCorrect: true },
      { label: "0.5", isCorrect: false },
      { label: "1", isCorrect: false },
    ],
    idealAnswer: "\u03c3'(z)=\u03c3(z)(1\u2212\u03c3(z)). At z=0, \u03c3(0)=0.5 so \u03c3'(0)=0.25 \u2014 the maximum of the sigmoid derivative. For |z|>5, \u03c3' drops below ~0.007, which drives vanishing gradients in deep sigmoid stacks.",
    explanation: "This calculation motivates why saturating activations struggle in deep nets.",
  },
  {
    categorySlug: "dl-basics",
    title: "SGD vs Momentum vs Adam",
    prompt: "What is the difference between SGD, SGD with momentum, and Adam?",
    roundLabel: "Q1.7",
    tags: "Optimizers",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Vanilla SGD: \u03b8 \u2190 \u03b8 \u2212 \u03b7\u2207L. Momentum adds inertia via an exponential moving average of gradients. Adam combines momentum with per-parameter adaptive learning rates (second-moment estimates). Adam is convenient; carefully scheduled SGD+momentum can still win on some ImageNet-style tasks.",
    explanation: "Know the trade-off between convenience (Adam) and peak generalization (tuned SGD).",
  },
  {
    categorySlug: "pytorch",
    title: "Conv2d Output Size with Same Padding",
    prompt: "What is the output size of Conv2d(3\u00d73, stride=1, padding=1) on a 256\u00d7256 image?",
    roundLabel: "Q2.1",
    tags: "CNN Geometry",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "254\u00d7254", isCorrect: false },
      { label: "256\u00d7256", isCorrect: true },
      { label: "258\u00d7258", isCorrect: false },
      { label: "128\u00d7128", isCorrect: false },
    ],
    idealAnswer: "(256 + 2\u00b71 \u2212 3)/1 + 1 = 256. With padding=1 and stride=1, spatial resolution is preserved \u2014 downsampling is then delegated to pooling or strided convs.",
    explanation: "Same-padding 3\u00d73 convolutions are the default building block in modern CNNs.",
  },
  {
    categorySlug: "architecture",
    title: "Why Max-Pooling Hurts Segmentation",
    prompt: "Why is max-pooling problematic for segmentation?",
    roundLabel: "Q2.2",
    tags: "Pooling",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Max-pooling discards precise spatial information. Classification (\u201cis there a tumor?\u201d) can tolerate that; pixel-wise segmentation (\u201cwhich pixels?\u201d) cannot. U-Net recovers detail via skip connections into the decoder.",
    explanation: "This motivates encoder\u2013decoder designs with skips.",
  },
  {
    categorySlug: "architecture",
    title: "Receptive Field of Stacked 3\u00d73 Convs",
    prompt: "A CNN has three Conv2d layers with 3\u00d73 kernels (no pooling). What is the receptive field of a neuron in layer 3?",
    roundLabel: "Q2.3",
    tags: "Receptive Field",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "3\u00d73", isCorrect: false },
      { label: "5\u00d75", isCorrect: false },
      { label: "7\u00d77", isCorrect: true },
      { label: "9\u00d79", isCorrect: false },
    ],
    idealAnswer: "7\u00d77. Each additional 3\u00d73 layer grows the RF by 2 per side (3+2+2). Many small 3\u00d73 layers (VGG-style) match a large kernel\u2019s RF with more nonlinearity and fewer parameters.",
    explanation: "RF growth without pooling is additive in (k\u22121) per layer.",
  },
  {
    categorySlug: "pytorch",
    title: "Conv2d Parameter Count",
    prompt: "Compute the number of parameters of Conv2d(64\u2192128, kernel=5\u00d75, bias=True).",
    roundLabel: "Q2.5",
    tags: "Parameter Counting",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "204,800", isCorrect: false },
      { label: "204,928", isCorrect: true },
      { label: "160,000", isCorrect: false },
      { label: "128\u00d764 = 8,192", isCorrect: false },
    ],
    idealAnswer: "Weights: 128\u00d764\u00d75\u00d75 = 204,800. Bias: 128. Total = 204,928.",
    explanation: "Parameters = Cout \u00d7 Cin \u00d7 Kh \u00d7 Kw (+ Cout if bias).",
  },
  {
    categorySlug: "architecture",
    title: "Global Average Pooling vs Average Pooling",
    prompt: "How does Global Average Pooling (GAP) differ from ordinary average pooling?",
    roundLabel: "Q2.6",
    tags: "Pooling",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Ordinary avg pool uses a fixed window (e.g. 2\u00d72) and keeps a reduced spatial map. GAP averages each entire feature map to one scalar per channel (H\u00d7W \u2192 1\u00d71), often replacing large FC classifiers and reducing parameters/overfitting.",
    explanation: "GAP is common in ResNet-style classification heads.",
  },
  {
    categorySlug: "pytorch",
    title: "Output Size Without Padding",
    prompt: "What happens to spatial size when a 224\u00d7224 image goes through Conv2d(3\u00d73, stride=1, padding=0)?",
    roundLabel: "Q2.7",
    tags: "CNN Geometry",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "224\u00d7224", isCorrect: false },
      { label: "222\u00d7222", isCorrect: true },
      { label: "221\u00d7221", isCorrect: false },
      { label: "112\u00d7112", isCorrect: false },
    ],
    idealAnswer: "Output is 222\u00d7222: (224 \u2212 3)/1 + 1 = 222. Without padding, each 3\u00d73 conv shrinks height/width by 2.",
    explanation: "Valid convolution reduces spatial dimensions.",
  },
  {
    categorySlug: "architecture",
    title: "Effective Receptive Field with Pooling",
    prompt: "A CNN has five 3\u00d73 conv layers with a 2\u00d72 max-pool between each. Roughly how much of the input does a neuron in layer 5 \u201csee\u201d?",
    roundLabel: "Q2.8",
    tags: "Receptive Field",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Pooling multiplies stride/effective RF growth. After several pool stages the RF becomes large (tens to >100 pixels depending on exact layout). Intuition: early layers see local texture; deep layers see object-scale context.",
    explanation: "Pooling expands the effective receptive field much faster than conv alone.",
  },
  {
    categorySlug: "architecture",
    title: "Where FLOPs Concentrate in CNNs",
    prompt: "Why are FLOPs in deep CNNs often dominated by early layers even though later layers have more channels?",
    roundLabel: "Q2.9",
    tags: "Compute",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Early feature maps are spatially large. Cost scales with H\u00d7W\u00d7Cin\u00d7Cout\u00d7K\u00b2. Later layers have more channels but much smaller H\u00d7W after pooling, so early high-resolution stages can dominate compute.",
    explanation: "This drives design choices like reducing early resolution carefully.",
  },
  {
    categorySlug: "architecture",
    title: "How ResNet Addresses Vanishing Gradients",
    prompt: "Why does ResNet address the vanishing-gradient problem?",
    roundLabel: "Q3.1",
    tags: "ResNet",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Residual skip connections provide an identity path so gradients can flow directly to earlier layers. Layers learn residual functions F(x) rather than full transforms, easing optimization of very deep nets.",
    explanation: "Identity shortcuts are the key ResNet idea (He et al., 2015).",
  },
  {
    categorySlug: "ai-dl",
    title: "Lower Learning Rate When Fine-Tuning",
    prompt: "Why use a smaller learning rate when fine-tuning than when training from scratch?",
    roundLabel: "Q3.2",
    tags: "Transfer Learning",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Pretrained features are already useful; a large LR can destroy them (catastrophic forgetting). Smaller LR makes gentle updates, often with a higher LR only on the new head.",
    explanation: "Differential learning rates for backbone vs head are common practice.",
  },
  {
    categorySlug: "ai-dl",
    title: "Fine-Tuning Overfitting Gap",
    prompt: "Your fine-tuned model reaches 99% train accuracy but only 62% validation accuracy. What is going wrong and what do you try?",
    roundLabel: "Q3.3",
    tags: "Overfitting",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Overfitting \u2014 especially likely with small medical datasets. Try stronger regularization (dropout, weight decay), heavier augmentation, freeze more backbone layers, reduce model capacity, early stopping, or more data.",
    explanation: "Train/val gaps demand regularization and data, not just more epochs.",
  },
  {
    categorySlug: "pytorch",
    title: "BatchNorm Train vs Eval Behavior",
    prompt: "Why does BatchNorm behave differently at inference than during training?",
    roundLabel: "Q3.4",
    tags: "BatchNorm",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Training uses batch statistics (mean/var). Inference uses running averages accumulated during training so predictions are deterministic and batch-size independent. Forgetting model.eval() is a common bug.",
    explanation: "Always switch to eval mode (and no_grad) for inference.",
  },
  {
    categorySlug: "pytorch",
    title: "BatchNorm2d Parameter Count",
    prompt: "How many parameters does BatchNorm2d with 128 channels have?",
    roundLabel: "Q3.5",
    tags: "BatchNorm",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "128", isCorrect: false },
      { label: "256 learnable (\u03b3, \u03b2); running stats are buffers", isCorrect: true },
      { label: "128\u00d7128", isCorrect: false },
      { label: "0 \u2014 BatchNorm has no parameters", isCorrect: false },
    ],
    idealAnswer: "Two learnable parameters per channel (\u03b3 scale and \u03b2 shift) \u2192 256 learnable params. Running mean/var (256 values) are buffers, not trained by gradient descent.",
    explanation: "BN adds negligible parameter count vs conv layers.",
  },
  {
    categorySlug: "architecture",
    title: "GoogLeNet Efficiency vs VGG-16",
    prompt: "Why can GoogLeNet (~7M params) outperform VGG-16 (~138M params) despite fewer parameters?",
    roundLabel: "Q3.6",
    tags: "Inception",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Inception modules use 1\u00d71 bottlenecks and multi-scale parallel convolutions for better parameter efficiency and multi-scale features, whereas VGG stacks large FC-heavy blocks that over-parameterize.",
    explanation: "Architecture design often beats raw parameter count.",
  },
  {
    categorySlug: "ai-dl",
    title: "Small Medical Dataset: ResNet-152 vs Small CNN",
    prompt: "For retinal classification with only 800 images, choose: ResNet-152 from scratch or a small CNN / pretrained ResNet with fine-tuning \u2014 and why?",
    roundLabel: "Q3.7",
    tags: "Transfer Learning",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "Train ResNet-152 from scratch for maximum capacity", isCorrect: false },
      { label: "Use pretrained ResNet / smaller model with fine-tuning", isCorrect: true },
      { label: "Only SVMs are valid under 1000 images", isCorrect: false },
      { label: "Always prefer the deepest model available", isCorrect: false },
    ],
    idealAnswer: "Prefer transfer learning with a pretrained ResNet (or a small CNN). ResNet-152 from scratch will overfit severely on 800 images. Pretraining on ImageNet provides useful early filters; fine-tune carefully.",
    explanation: "Data scale drives model choice in medical imaging.",
  },
  {
    categorySlug: "architecture",
    title: "U-Net Skip Concatenation vs Addition",
    prompt: "Why do U-Net skip connections concatenate features instead of adding them as in ResNet?",
    roundLabel: "Q4.1",
    tags: "U-Net",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Concatenation preserves encoder feature channels so the decoder can re-learn how to combine fine details with upsampled semantics. Addition forces same channel count and mixes signals immediately; U-Net prioritizes detail recovery for dense prediction.",
    explanation: "Concat skips are characteristic of U-Net; ResNet uses additive identity skips.",
  },
  {
    categorySlug: "architecture",
    title: "Why Pixel Accuracy Fails in Medical Segmentation",
    prompt: "Why is pixel accuracy insufficient as a metric for medical segmentation?",
    roundLabel: "Q4.2",
    tags: "Metrics",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Background dominates (often >95% of voxels). A model predicting all background can score high accuracy while missing the lesion. Prefer Dice/IoU, sensitivity/specificity, and clinically relevant surface or volume errors.",
    explanation: "Class imbalance makes accuracy misleading.",
  },
  {
    categorySlug: "architecture",
    title: "ConvTranspose2d vs Upsample",
    prompt: "What is the difference between ConvTranspose2d and a simple Upsample?",
    roundLabel: "Q4.3",
    tags: "Upsampling",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Upsample (nearest/bilinear) resizes without learned parameters. ConvTranspose2d (deconvolution) learns upsampling kernels and can introduce checkerboard artifacts if poorly configured. Many modern U-Nets upsample then Conv instead of ConvTranspose.",
    explanation: "Know artifact risks of transposed convolutions.",
  },
  {
    categorySlug: "architecture",
    title: "High Dice but Clinically Wrong Boundary",
    prompt: "Dice is 0.85 for bladder segmentation, but the surgeon says the model is useless. Why can that happen?",
    roundLabel: "Q4.4",
    tags: "Clinical Metrics",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Dice rewards overlap volume; a small systematic boundary error near critical structures (ureters, tumor margins) can still be clinically unacceptable. Report Hausdorff distance / surface metrics and review failure cases with clinicians.",
    explanation: "Overlap metrics \u2260 clinical utility.",
  },
  {
    categorySlug: "architecture",
    title: "Compute Dice from Overlap Counts",
    prompt: "Compute Dice for: GT = 500 voxels, prediction = 550 voxels, overlap = 400 voxels.",
    roundLabel: "Q4.5",
    tags: "Dice",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "0.85", isCorrect: false },
      { label: "\u2248 0.76", isCorrect: true },
      { label: "0.40", isCorrect: false },
      { label: "1.0", isCorrect: false },
    ],
    idealAnswer: "Dice = 2|P\u2229G| / (|P|+|G|) = 2\u00b7400 / (550+500) = 800/1050 \u2248 0.762.",
    explanation: "Always use the 2|\u2229|/(|P|+|G|) definition.",
  },
  {
    categorySlug: "architecture",
    title: "Tversky Loss in Oncology",
    prompt: "What is Tversky loss and why can it be more useful than Dice in oncology?",
    roundLabel: "Q4.6",
    tags: "Loss Functions",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Tversky generalizes Dice with weights on false positives vs false negatives. In oncology you may penalize false negatives more (missed tumor) by emphasizing sensitivity \u2014 something standard Dice treats symmetrically.",
    explanation: "Tunable FP/FN trade-off matters for screening vs confirmation use cases.",
  },
  {
    categorySlug: "architecture",
    title: "Why U-Net Became Standard in Medicine",
    prompt: "Why did the original U-Net paper (Ronneberger et al., 2015) become so influential in medical imaging?",
    roundLabel: "Q4.7",
    tags: "U-Net History",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "It delivers strong segmentation with relatively little labeled data via elastic augmentation, symmetric encoder\u2013decoder design, and skip connections that restore spatial detail \u2014 matching medical needs (small data, precise boundaries).",
    explanation: "U-Net is still the default baseline for biomedical segmentation.",
  },
  {
    categorySlug: "architecture",
    title: "Attention U-Net Motivation",
    prompt: "What is an Attention U-Net and which problem does it address?",
    roundLabel: "Q4.8",
    tags: "Attention U-Net",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "It inserts attention gates on skip pathways so the decoder emphasizes salient regions and suppresses irrelevant background before concatenation \u2014 helping focus on organs/lesions and reducing noise from skips.",
    explanation: "Attention gates are a lightweight way to filter skip features.",
  },
  {
    categorySlug: "medical-data",
    title: "Why Not Vertical Flip on Chest X-rays",
    prompt: "Why should you not vertically flip images when training a chest X-ray classifier?",
    roundLabel: "Q5.1",
    tags: "Augmentation",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "Vertical flips always improve invariance", isCorrect: false },
      { label: "They create anatomically implausible orientations", isCorrect: true },
      { label: "DICOM forbids all flips", isCorrect: false },
      { label: "Only vertical flips are allowed, not horizontal", isCorrect: false },
    ],
    idealAnswer: "Vertical flips create anatomically impossible orientations (apex/base reversed), teaching spurious features. Horizontal flips may be acceptable with care; vertical flips generally are not for upright chest radiographs.",
    explanation: "Augmentations must respect anatomical plausibility.",
  },
  {
    categorySlug: "governance",
    title: "In-House vs External Performance Drop",
    prompt: "Your model reaches Dice 0.92 in-house but 0.71 on an external test set. The department head asks why. What do you answer?",
    roundLabel: "Q5.2",
    tags: "Generalization",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Domain shift: different scanners, protocols, demographics, labeling styles. In-house metrics overestimate generalization. Need multi-center validation, harmonization, and possibly domain adaptation \u2014 not just more epochs on internal data.",
    explanation: "External validation is mandatory for credible clinical claims.",
  },
  {
    categorySlug: "governance",
    title: "Grad-CAM Is Not Causality Proof",
    prompt: "A Grad-CAM heatmap highlights the nodule correctly. Can you conclude the model is clinically trustworthy?",
    roundLabel: "Q5.3",
    tags: "Explainability",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "No. Saliency can look right for wrong reasons (shortcuts, correlations). Need proper validation, failure analysis, calibration, and clinical studies. Explainability heatmaps are supportive evidence, not proof of safe decision-making.",
    explanation: "XAI visualizations \u2260 regulatory or clinical validation.",
  },
  {
    categorySlug: "ct-mri",
    title: "2.5D Processing for Anisotropic MRI",
    prompt: "Why is 2.5D processing a good compromise for anisotropic MRI?",
    roundLabel: "Q5.4",
    tags: "2.5D MRI",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Full 3D convs are memory-heavy and may poorly match thick-slice anisotropy. 2.5D (multi-slice 2D inputs or pseudo-3D) captures some through-plane context at far lower cost and often works well when z-spacing is large.",
    explanation: "2.5D sits between pure 2D and expensive isotropic 3D.",
  },
  {
    categorySlug: "ai-dl",
    title: "Accuracy on Imbalanced Data",
    prompt: "A colleague reports 98% accuracy on a dataset with 95% class imbalance. Why is this unimpressive?",
    roundLabel: "Q5.5",
    tags: "Metrics",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "98% accuracy proves clinical readiness", isCorrect: false },
      { label: "A trivial majority classifier already gets ~95%", isCorrect: true },
      { label: "Accuracy is unaffected by imbalance", isCorrect: false },
      { label: "Imbalance only matters for regression", isCorrect: false },
    ],
    idealAnswer: "A majority-class classifier scores ~95% accuracy by predicting only the frequent class. Report balanced accuracy, AUROC/AUPRC, sensitivity/specificity, or Dice for segmentation.",
    explanation: "Always compare against a trivial baseline under imbalance.",
  },
  {
    categorySlug: "ai-dl",
    title: "Limits of MC Dropout Uncertainty",
    prompt: "Why can MC Dropout capture only part of model uncertainty?",
    roundLabel: "Q5.6",
    tags: "Uncertainty",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "MC Dropout approximates epistemic uncertainty from the approximate posterior over weights, but poorly covers data/aleatoric noise and can be miscalibrated. It is not a full Bayesian treatment; ensemble and dedicated likelihood models may be needed.",
    explanation: "Know epistemic vs aleatoric uncertainty.",
  },
  {
    categorySlug: "ct-mri",
    title: "Memory Footprint of a 3D CT Volume",
    prompt: "Compute the memory size of a 512\u00d7512\u00d7300 CT volume in float32.",
    roundLabel: "Q5.7",
    tags: "Memory",
    type: QuestionType.MULTIPLE_CHOICE,
    choices: [
      { label: "\u2248 75 MB", isCorrect: false },
      { label: "\u2248 300 MB (\u2248 314.6 MB)", isCorrect: true },
      { label: "\u2248 1.2 GB", isCorrect: false },
      { label: "\u2248 12 MB", isCorrect: false },
    ],
    idealAnswer: "512\u00d7512\u00d7300 = 78,643,200 voxels \u00d7 4 bytes = 314,572,800 bytes \u2248 300 MiB (about 314 MB decimal). Training activations/gradients multiply this cost substantially.",
    explanation: "This motivates patch training and mixed precision.",
  },
  {
    categorySlug: "ai-dl",
    title: "Ensemble vs Bagging",
    prompt: "What is the difference between an ensemble and a bagging prediction?",
    roundLabel: "Q5.8",
    tags: "Ensembles",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Ensemble is the general idea of combining models. Bagging is a specific ensemble recipe: bootstrap resample training sets, train base learners, aggregate (e.g. average/vote). Not every ensemble uses bagging (e.g. snapshot ensembles, different architectures).",
    explanation: "Bagging \u2282 ensembles.",
  },
  {
    categorySlug: "governance",
    title: "Retrospective vs Prospective Clinical Evaluation",
    prompt: "What is the most important difference between retrospective and prospective clinical evaluation of an ML model?",
    roundLabel: "Q5.9",
    tags: "Clinical Validation",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "Retrospective: model run on historical data already collected. Prospective: model evaluated on future real-world cases as care unfolds \u2014 closer to deployment conditions and required for credible clinical evidence.",
    explanation: "Prospective studies better stress-test workflow and distribution shift.",
  },
  {
    categorySlug: "governance",
    title: "When Federated Learning Is Not Enough",
    prompt: "In which situations is federated learning not the right answer to data-protection constraints?",
    roundLabel: "Q5.10",
    tags: "Federated Learning",
    type: QuestionType.FREE_TEXT,
    idealAnswer: "When sites cannot run local training infra, labels are missing/inconsistent, legal basis still blocks any collaborative training, or the main problem is lack of expertise/quality rather than raw data movement. FL does not magically fix poor labels or non-IID collapse without careful design.",
    explanation: "FL addresses data locality, not every governance or quality problem.",
  },
];
